### ISSUE TITLE
M5_JoyC with M5StickCPlus does not work with Arduino ESP library

### ISSUE THREAD

**Issue by shmoun** [m5stack/M5_JoyC#2]
After compilation of M5_JoyC example code with Arduino IDE and ESP libraries installed, the stick didn't seem to read anything from the M5_JoyC hat.

The patch in this pull request fixes the issue: https://github.com/m5stack/M5_JoyC/pull/1

**Comment by TinyuZhao** [comment]
Thank you for your help!
